version: '3'

services: 
  discovery: 
    image: fsd/discovery
    ports:
    - "8761:8761"
    environment:
    - JAVA_OPTS= -Dspring.profiles.active=docker
    
  discovery2: 
    image: fsd/discovery
    ports:
    - "8761"
    environment:
    - JAVA_OPTS= -Dspring.profiles.active=docker2
    links:
    - discovery
    
  gateway:
    image: fsd/gateway
    ports:
    - "8000:8080"
    environment:
    - JAVA_OPTS= -Dspring.profiles.active=docker
    links:
    - discovery2

  config:
    image: fsd/config
    ports:
    - "8080"
    environment:
    - JAVA_OPTS= -Dspring.profiles.active=docker
    links:
    - discovery2
    - gateway
    
  mq: 
    image: rabbitmq:3-management
    ports:
    - "4369:4369"
    - "5671-5672:5671-5672"
    - "15671-15672:15671-15672"
    - "25672:25672"
    
  mongo: 
    image: mongo
    ports:
    - "27017:27017"
    
  multimedia:
    image: fsd/multimedia
    ports:
    - "8080"
    environment:
    - JAVA_OPTS= -Dspring.profiles.active=docker
    links:
    - discovery2
    - config
    - mq
    - mongo
    
  library:
    image: fsd/library
    ports:
    - "8080"
    environment:
    - JAVA_OPTS= -Dspring.profiles.active=docker
    links:
    - discovery2
    - config

  ui-library:
    build: "ui-library" 
    ports:
    - "4200:4200"
    links:
    - gateway
    
    